### List Manipulation

In [1]:
fruits = ["apple", 1.5, "banana", 0.98, "strawberry", 3.49]
fruits

['apple', 1.5, 'banana', 0.98, 'strawberry', 3.49]

In [2]:
# Extend the list
fruits = fruits + ["mango", 1.69]
fruits

['apple', 1.5, 'banana', 0.98, 'strawberry', 3.49, 'mango', 1.69]

In [3]:
# Delete items from the list
del(fruits[0:2])
fruits

['banana', 0.98, 'strawberry', 3.49, 'mango', 1.69]

In [4]:
# When you copy x to y, you’re copying the reference, not the value itself.
smoothies = fruits
del(smoothies[0:2])
print("Make smoothies: ", smoothies)
print("Buy fruits: ", fruits)

Make smoothies:  ['strawberry', 3.49, 'mango', 1.69]
Buy fruits:  ['strawberry', 3.49, 'mango', 1.69]


In [5]:
# To create a new list, use:
smoothies_new = list(smoothies)
del(smoothies_new[0:2])
print(smoothies_new, smoothies)

['mango', 1.69] ['strawberry', 3.49, 'mango', 1.69]


In [6]:
# Or use:
fruits_new = fruits[:]
del(fruits_new[0:2])
print(fruits_new, fruits)

['mango', 1.69] ['strawberry', 3.49, 'mango', 1.69]


In [7]:
# List Methods
print(fruits.index("mango"))
print(fruits.count("mango"))

2
1


### Numpy

In [8]:
import numpy as np

In [9]:
x = [2.5, 3.2, 5.4, 0.7]
type(x)

list

In [10]:
np_x = np.array(x)
np_x

array([ 2.5,  3.2,  5.4,  0.7])

In [11]:
print(x + x)
print(np_x + np_x)

[2.5, 3.2, 5.4, 0.7, 2.5, 3.2, 5.4, 0.7]
[  5.    6.4  10.8   1.4]


In [12]:
type(np_x)

numpy.ndarray

In [13]:
np_x.shape

(4,)

### Dictionary

In [14]:
dict_fruits = {"apple": 1.5, "banana": 0.98, "strawberry": 3.49}
dict_fruits["apple"]

1.5

In [15]:
dict_fruits.keys()

dict_keys(['banana', 'apple', 'strawberry'])

In [16]:
dict_fruits["mango"] = 1.69
"mango" in dict_fruits

True

In [17]:
del(dict_fruits["banana"])
dict_fruits

{'apple': 1.5, 'mango': 1.69, 'strawberry': 3.49}

### List vs Dictionary Summary

In [18]:
from IPython.display import HTML, display
import tabulate

In [19]:
table = [["List", "Dictionary"],
         ["Select, update and remove: []", "Select, update and remove: []"],
         ["Delete: del()", "Delete: del()"],
         ["Indexed by range of numbers", "Indexed by unique keys"],
         ["Collection of values; order matters",
          "Lookup table with unique keys"]]
display(HTML(tabulate.tabulate(table, tablefmt='html', 
                               headers="firstrow", 
                               stralign = 'center')), )

### Sort dictionaries

It is not possible to sort a dictionary, only to get a representation of a dictionary that is sorted. Dictionaries are inherently orderless, but other types, such as lists and tuples, are not. So you need an ordered data type to represent sorted values, which will be a list—probably a list of tuples.

Reference: https://stackoverflow.com/questions/613183/how-do-i-sort-a-dictionary-by-value

#### Solution 1: operator package

In [20]:
import operator

In [21]:
mydict = {'c': 45,
        'f': 32,
        'a': 80,
        'z': 10}
mydict

{'a': 80, 'c': 45, 'f': 32, 'z': 10}

**Use sorted() to sort by key**

Note: Need to indicate reverse=Ture in sorted() while using the code below to sort accendingly.

In [22]:
sorted_mydict = sorted(mydict.items(), 
                       key=operator.itemgetter(1), 
                       reverse = True)
sorted_mydict

[('a', 80), ('c', 45), ('f', 32), ('z', 10)]

In [23]:
mydict.items()

dict_items([('f', 32), ('c', 45), ('z', 10), ('a', 80)])

**Use sorted() to sort by value**

In [24]:
sorted_mydict_byvalue = sorted(mydict.items(), key=operator.itemgetter(0))
sorted_mydict_byvalue

[('a', 80), ('c', 45), ('f', 32), ('z', 10)]

#### Solution 2: anonymous function

In [25]:
sorted(mydict.items(), key=lambda x: x[0])

[('a', 80), ('c', 45), ('f', 32), ('z', 10)]

In [26]:
sorted(mydict.items(), key=lambda x: x[1])

[('z', 10), ('f', 32), ('c', 45), ('a', 80)]

### for loop / enumerate

In [27]:
fam = [1.73, 1.68, 1.74, 1.82]
for index, height in enumerate(fam):
    print("index " + str(index) + ": " + str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.74
index 3: 1.82


In [28]:
help(enumerate)

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable[, start]) -> iterator for index, value of iterable
 |  
 |  Return an enumerate object.  iterable must be another object that supports
 |  iteration.  The enumerate object yields pairs containing a count (from
 |  start, which defaults to zero) and a value yielded by the iterable argument.
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.



**items()**

In [32]:
# Use items() to loop dictionary
for fruit, price in dict_fruits.items():
    print(fruit + ": " + str(price))

apple: 1.5
strawberry: 3.49
mango: 1.69


**np.nditer()**

In [37]:
# For 2D arrays, for loop prints out two arrays one by one. 
# To print out the values in each array one by one, use np.nditer().
np_xy = np.array([[15, 23, 18, 40],
                  [3, 5, 8, 12]])
for val in np_xy:
    print(val)

[15 23 18 40]
[ 3  5  8 12]


In [38]:
for val in np.nditer(np_xy):
    print(val)

15
23
18
40
3
5
8
12


### User-defined Functions
Docstrings describe what your function does and serve as documentation for your function. It's placed in the immediate line after the function heder and in between triple double quotes """.

In [ ]:
def square(value):
    """Return the square of a value."""
    new_value = value ** 2
    return new value

### Tuples
- Like a list - can contain multiple values
- Immutable - can't modiy values!
- Use tuples to make functions return multiple values.

In [40]:
# Unpacking tuples
nums = (2, 5, 8)
a, b, c = nums
print(a)

2


### Python's built-in scope

In [42]:
import builtins
dir(builtins)[:10]

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError']

### Name an anonymous function

In [44]:
echo_word = (lambda word, echo: word * echo)
echo_word('hey', 5)

'heyheyheyheyhey'

### filter()
The result of filter() needs to be converted to a list. Otherwise, it is just a filter object.

In [45]:
houses = ['Targaryen', 'Stark', 'Lannister', 'Greyjoy', 
          'Arryn', 'Baratheon', 'Tully', 'Tyrell', 'Martell']
result = filter(lambda x: len(x) > 7, houses)
print(result)
print(list(result))

['Targaryen', 'Lannister', 'Baratheon']


### enumerate(), zip(), and unpack()

In [46]:
house = enumerate(houses)
print(type(house))

<class 'enumerate'>


In [47]:
print(list(house))

[(0, 'Targaryen'), (1, 'Stark'), (2, 'Lannister'), (3, 'Greyjoy'), (4, 'Arryn'), (5, 'Baratheon'), (6, 'Tully'), (7, 'Tyrell'), (8, 'Martell')]


In [49]:
sigils = ['Dragon', 'Direwolf', 'Lion', 'Kraken', 
          'Falcon', 'Stag', 'Trout', 'Rose', 'Sunspear']
z = zip(houses, sigils)
print(type(z))
print(list(z))

<class 'zip'>
[('Targaryen', 'Dragon'), ('Stark', 'Direwolf'), ('Lannister', 'Lion'), ('Greyjoy', 'Kraken'), ('Arryn', 'Falcon'), ('Baratheon', 'Stag'), ('Tully', 'Trout'), ('Tyrell', 'Rose'), ('Martell', 'Sunspear')]


In [59]:
z = zip(houses, sigils)
for house, sigil in z:
    print(house, sigil)

Targaryen Dragon
Stark Direwolf
Lannister Lion
Greyjoy Kraken
Arryn Falcon
Baratheon Stag
Tully Trout
Tyrell Rose
Martell Sunspear


In [61]:
z = zip(houses, sigils)
print(*z)

('Targaryen', 'Dragon') ('Stark', 'Direwolf') ('Lannister', 'Lion') ('Greyjoy', 'Kraken') ('Arryn', 'Falcon') ('Baratheon', 'Stag') ('Tully', 'Trout') ('Tyrell', 'Rose') ('Martell', 'Sunspear')


In [62]:
# Using * and zip to 'unzip'
z = zip(houses, sigils)
result1, result2 = zip(*z)
print(result1)
print(result2)

('Targaryen', 'Stark', 'Lannister', 'Greyjoy', 'Arryn', 'Baratheon', 'Tully', 'Tyrell', 'Martell')
('Dragon', 'Direwolf', 'Lion', 'Kraken', 'Falcon', 'Stag', 'Trout', 'Rose', 'Sunspear')


### List Comprehension

In [69]:
nums = [12, 5, 8, 39, 20]
[round(num * 0.8, 2) for num in nums]

[9.6, 4.0, 6.4, 31.2, 16.0]

In [68]:
# Create a 5 x 5 matrix using a list of lists: matrix
matrix = [[i for i in range(5)] for i in range(5)]
for row in matrix:
    print(row)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]


In [72]:
# Conditionals in comprehensions
[num + 10 if num <10 else num for num in nums]

[12, 15, 18, 39, 20]

In [73]:
# Conditionals on the iterable
[num * 2 for num in nums if num < 10]

[10, 16]

### Generator
Lazy evaluation – the value of the evaluation is delayed until the value is needed. This would help when dealing with extremely large sequences since you don’t want to store the entire list in the memory.

In [74]:
# List comprehension
[2 * num for num in range(10)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [75]:
# Use () instead of []
(2 * num for num in range(10))

<generator object <genexpr> at 0x0000020FB4772FC0>

In [76]:
# print values for generators
result = (2 * num for num in range(10))
print(next(result))
print(next(result))

0
2


### Generator vs. List comprehensions
A generator for large sequences could be easily created because it does not yet create the entire list. Anything we can do on a list comprehension can also be done on a generator expression. However, generator could be more efficient to process large iterators. Remember to convert a generator to a list when printing it out.